"""FC-2 · Family handover pack PDF.

A single-click pack for when the primary caregiver is unavailable. Pulls the
participant's upcoming services, open tasks, recorded care preferences and open
issues into one print-ready document.
"""
from __future__ import annotations

import io
from datetime import datetime, timezone
from typing import Any, Dict, List

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, KeepTogether

TEAL = colors.HexColor("#0E4D52")

_PURPOSE_LABEL = {
    "primary_caregiver_absence": "Primary caregiver is away",
    "hospital_visit": "Hospital visit",
    "provider_change": "Provider change",
    "other": "Handover",
}
_CATEGORY_LABEL = {
    "preferences_care_style": "Care style",
    "preferences_daily_routine": "Daily routine",
    "preferences_communication": "Communication",
    "values_and_dignity": "Values and dignity",
}


def _fmt(v) -> str:
    if not v:
        return ""
    try:
        return datetime.fromisoformat(str(v).replace("Z", "+00:00")).strftime("%a %d %b, %I:%M %p")
    except Exception:
        return str(v)[:16]


def render_family_handover_pdf(*, participant_name: str, purpose: str, purpose_notes: str,
                               tasks: List[Dict[str, Any]], upcoming: List[Dict[str, Any]],
                               preferences: List[Dict[str, Any]], incidents: List[Dict[str, Any]]) -> bytes:
    buf = io.BytesIO()
    styles = getSampleStyleSheet()
    h1 = ParagraphStyle("h1", parent=styles["Heading1"], fontSize=18, textColor=TEAL, spaceAfter=4)
    h2 = ParagraphStyle("h2", parent=styles["Heading2"], fontSize=13, textColor=TEAL, spaceBefore=12, spaceAfter=4)
    body = ParagraphStyle("body", parent=styles["BodyText"], fontSize=10, leading=14)
    small = ParagraphStyle("small", parent=body, fontSize=9, textColor=colors.HexColor("#555"))

    doc = SimpleDocTemplate(buf, pagesize=A4, leftMargin=1.8 * cm, rightMargin=1.8 * cm,
                            topMargin=2.2 * cm, bottomMargin=2.2 * cm,
                            title=f"Family handover pack, {participant_name}")
    story: List[Any] = []
    story.append(Paragraph("Family handover pack", h1))
    story.append(Paragraph(f"For: <b>{participant_name}</b>", body))
    story.append(Paragraph(f"Reason: {_PURPOSE_LABEL.get(purpose, 'Handover')}", small))
    if purpose_notes:
        story.append(Paragraph(purpose_notes, small))
    story.append(Paragraph(f"Generated: {datetime.now(timezone.utc).strftime('%d/%m/%Y %H:%M')}", small))

    def _list_section(title, rows, render):
        story.append(Paragraph(title, h2))
        if not rows:
            story.append(Paragraph("Nothing recorded.", small))
            return
        data = [[Paragraph(render(r), body)] for r in rows]
        t = Table(data, colWidths=[16.4 * cm], hAlign="LEFT")
        t.setStyle(TableStyle([
            ("BOX", (0, 0), (-1, -1), 0.4, colors.HexColor("#DDD")),
            ("INNERGRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#EEE")),
            ("LEFTPADDING", (0, 0), (-1, -1), 6), ("RIGHTPADDING", (0, 0), (-1, -1), 6),
            ("TOPPADDING", (0, 0), (-1, -1), 4), ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ]))
        story.append(KeepTogether(t))

    _list_section("Upcoming services", upcoming,
                  lambda e: f"<b>{_fmt(e.get('start_datetime'))}</b> — {e.get('title','Service')}"
                            + (f" · {e.get('provider_name')}" if e.get('provider_name') else ""))
    _list_section("Open tasks", tasks,
                  lambda t: f"{t.get('title','')}"
                            + (f" (due {t.get('due_date')})" if t.get('due_date') else "")
                            + (f" — {t.get('assignee_name')}" if t.get('assignee_name') else ""))
    _list_section("Care preferences", preferences,
                  lambda n: f"<b>{_CATEGORY_LABEL.get(n.get('category'), 'Preference')}:</b> {n.get('content','')}")
    _list_section("Open issues to be aware of", incidents,
                  lambda i: f"{i.get('summary','')} ({i.get('status','')})")

    story.append(Spacer(1, 0.5 * cm))
    story.append(Paragraph(
        "Generated by Wayly from information the household recorded. Not clinical advice.", small))

    def on_page(canvas, d):
        canvas.saveState()
        canvas.setFont("Helvetica", 8)
        canvas.setFillColor(colors.HexColor("#888"))
        canvas.drawRightString(A4[0] - 1.8 * cm, 1.2 * cm, f"Page {d.page}  ·  Wayly family handover")
        canvas.restoreState()

    doc.build(story, onFirstPage=on_page, onLaterPages=on_page)
    return buf.getvalue()
