/** @type {import('tailwindcss').Config} */
module.exports = {
    darkMode: ["class"],
    content: ["./src/**/*.{js,jsx,ts,tsx}", "./public/index.html"],
    theme: {
        extend: {
            fontFamily: {
                heading: ["Crimson Pro", "Georgia", "serif"],
                sans: ["IBM Plex Sans", "system-ui", "sans-serif"],
                mono: ["IBM Plex Mono", "ui-monospace", "monospace"],
            },
            borderRadius: {
                lg: "var(--radius)",
                md: "calc(var(--radius) - 2px)",
                sm: "calc(var(--radius) - 4px)",
            },
            colors: {
                background: "hsl(var(--background))",
                foreground: "hsl(var(--foreground))",
                card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
                popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
                primary: { DEFAULT: "hsl(var(--primary))", foreground: "hsl(var(--primary-foreground))" },
                secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
                muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
                accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
                destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
                border: "hsl(var(--border))",
                input: "hsl(var(--input))",
                ring: "hsl(var(--ring))",
                kindred: {
                    bg: "#EAF4FB",
                    surface: "#FFFFFF",
                    surface2: "#DCEBF7",
                    primary: "#0E2A47",
                    gold: "#2BC4D6",
                    sage: "#3DB8A8",
                    terracotta: "#E07A5F",
                    text: "#0E1F35",
                    muted: "#4A5A75",
                    border: "#CFE0F0",
                },
                wayly: {
                    navy: "#0E2A47",
                    blue: "#1E7BD9",
                    cyan: "#2BC4D6",
                    mint: "#6FE3DA",
                    sky: "#BFE0F5",
                    skyLight: "#EAF4FB",
                    wave: "#2E78C8",
                    indigo: "#5A7BE8",
                    lavender: "#8E7BE8",
                    coral: "#E07A5F",
                    teal: "#3DB8A8",
                },
            },
            keyframes: {
                "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
                "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
                "fade-up": {
                    "0%": { opacity: "0", transform: "translateY(10px)" },
                    "100%": { opacity: "1", transform: "translateY(0)" },
                },
            },
            animation: {
                "accordion-down": "accordion-down 0.2s ease-out",
                "accordion-up": "accordion-up 0.2s ease-out",
                "fade-up": "fade-up 0.6s ease-out both",
            },
        },
    },
    plugins: [require("tailwindcss-animate")],
};
