import React, { useCallback, useState } from "react";
import { RefreshControl, ScrollView, StyleSheet, View } from "react-native";
import { router, useFocusEffect } from "expo-router";
import { Mail, Clock, AlertTriangle, PenLine, ArrowUpRight, ArrowDownLeft } from "lucide-react-native";

import { AppHeader, Badge, Button, Card, Loading, StatePanel, T } from "@/src/components/ui";
import { PageIntro } from "@/src/components/PageIntro";
import { SmartAISummary } from "@/src/components/SmartAISummary";
import { useParticipants } from "@/src/context/ParticipantContext";
import { apiFetch } from "@/src/lib/api";
import { useTheme } from "@/src/theme/ThemeContext";
import { fonts, radius, spacing } from "@/src/theme/tokens";

type Entry = { id: string; archetype?: string; direction?: string; recipient_type?: string; status?: string; created_at?: string };
type FollowUp = { entry_id?: string; id?: string; archetype?: string; due_at?: string; recipient_type?: string; label?: string };

const ARCHETYPE_LABEL: Record<string, string> = {
  dispute: "Fee dispute", reassessment: "Reassessment request", complaint: "Complaint",
  service_change: "Service change", hardship: "Hardship notification", care_plan_amendment: "Care plan amendment",
  general: "General letter", response: "Response to provider", safeguarding: "Safeguarding record",
};
const RECIPIENT_LABEL: Record<string, string> = {
  provider_cm: "Provider (Care Manager)", provider: "Provider", mac: "My Aged Care",
  acqsc: "ACQSC", ombudsman: "Ombudsman", services_australia: "Services Australia",
};
const STATUS_TONE: Record<string, "neutral" | "success" | "alert" | "brand"> = {
  draft: "brand", sent: "success", awaiting_response: "alert", responded: "success", closed: "neutral",
};
function pretty(s?: string, map?: Record<string, string>): string {
  if (!s) return "";
  return (map && map[s]) || s.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
}
function fmt(s?: string): string {
  if (!s) return "";
  try { return new Date(s).toLocaleDateString("en-AU", { day: "numeric", month: "short", year: "numeric" }); }
  catch { return s; }
}

export default function LettersMailboxScreen() {
  const { colors } = useTheme();
  const { activeId } = useParticipants();
  const [entries, setEntries] = useState<Entry[]>([]);
  const [overdue, setOverdue] = useState<FollowUp[]>([]);
  const [upcoming, setUpcoming] = useState<FollowUp[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(false);
  const [refreshing, setRefreshing] = useState(false);

  const load = useCallback(async () => {
    setError(false);
    const q = activeId ? `?participant_id=${activeId}` : "";
    try {
      const [c, f] = await Promise.all([
        apiFetch<{ entries: Entry[] }>(`/lf1/correspondence${q}`).catch(() => ({ entries: [] })),
        apiFetch<{ overdue: FollowUp[]; upcoming: FollowUp[] }>(`/lf1/follow-ups${q}`).catch(() => ({ overdue: [], upcoming: [] })),
      ]);
      setEntries(c?.entries || []);
      setOverdue(f?.overdue || []);
      setUpcoming(f?.upcoming || []);
    } catch {
      setError(true);
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  }, [activeId]);

  useFocusEffect(useCallback(() => { load(); }, [load]));

  return (
    <View style={{ flex: 1, backgroundColor: colors.bg }}>
      <AppHeader title="Letters Mailbox" subtitle="Drafts, replies and follow-ups" onBack={() => router.back()} />
      {loading ? (
        <Loading label="Loading your mailbox…" />
      ) : error ? (
        <StatePanel testID="letters-error" icon={Mail} title="Couldn't load your mailbox" actionLabel="Retry" onAction={load} />
      ) : (
        <ScrollView
          contentContainerStyle={{ padding: spacing.lg, paddingBottom: spacing.xxl, gap: spacing.md }}
          refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => { setRefreshing(true); load(); }} tintColor={colors.primary} />}
        >
          <PageIntro
            eyebrow="Letters And Follow-Ups"
            title="Your Letter Mailbox"
            description="Every letter chain generated by Wayly, ready to review, edit, and send. Nothing is sent without your explicit click."
            whatItDoes="Groups drafts by the chain that generated them (hardship application, provider switch, CHSP dispute, complaint escalation) and gives you edit + send controls per draft."
          />
          <Button label="Draft a new letter" testID="letters-new" icon={PenLine} onPress={() => router.push("/tool/letters-and-follow-ups")} />

          {entries.length > 0 || overdue.length > 0 || upcoming.length > 0 ? (
            <SmartAISummary
              pageKey="letters-mailbox"
              context={{
                entry_count: entries.length,
                overdue_followups: overdue.length,
                upcoming_followups: upcoming.length,
                by_status: entries.reduce((acc: Record<string, number>, e) => {
                  const k = e.status || "unknown";
                  acc[k] = (acc[k] || 0) + 1;
                  return acc;
                }, {}),
              }}
            />
          ) : null}

          {overdue.length > 0 ? (
            <Card testID="letters-overdue" style={{ backgroundColor: colors.errorSoft, borderColor: colors.errorSoft }}>
              <View style={{ flexDirection: "row", alignItems: "center", gap: 8, marginBottom: spacing.sm }}>
                <AlertTriangle size={18} color={colors.terracotta} />
                <T style={{ fontFamily: fonts.bodySemi, color: colors.terracotta }}>Overdue follow-ups ({overdue.length})</T>
              </View>
              {overdue.map((f, i) => (
                <T key={f.entry_id || f.id || i} variant="small" style={{ color: colors.text, marginTop: 2 }}>
                  • {pretty(f.archetype, ARCHETYPE_LABEL) || f.label || "Follow-up"}{f.due_at ? ` · due ${fmt(f.due_at)}` : ""}
                </T>
              ))}
            </Card>
          ) : null}

          {upcoming.length > 0 ? (
            <Card testID="letters-upcoming">
              <View style={{ flexDirection: "row", alignItems: "center", gap: 8, marginBottom: spacing.sm }}>
                <Clock size={18} color={colors.gold} />
                <T style={{ fontFamily: fonts.bodySemi }}>Upcoming follow-ups ({upcoming.length})</T>
              </View>
              {upcoming.map((f, i) => (
                <T key={f.entry_id || f.id || i} variant="small" style={{ marginTop: 2 }}>
                  • {pretty(f.archetype, ARCHETYPE_LABEL) || f.label || "Follow-up"}{f.due_at ? ` · due ${fmt(f.due_at)}` : ""}
                </T>
              ))}
            </Card>
          ) : null}

          <T variant="label" style={{ marginTop: spacing.sm }}>ALL LETTERS</T>
          {entries.length === 0 ? (
            <StatePanel testID="letters-empty" icon={Mail} title="No letters yet" message="Draft your first letter and it will live here with follow-up reminders." actionLabel="Draft a letter" onAction={() => router.push("/tool/letters-and-follow-ups")} />
          ) : (
            entries.map((e) => {
              const inbound = e.direction === "inbound";
              const DirIcon = inbound ? ArrowDownLeft : ArrowUpRight;
              return (
                <Card key={e.id} testID={`letter-${e.id}`}>
                  <View style={{ flexDirection: "row", justifyContent: "space-between", gap: 8 }}>
                    <View style={{ flexDirection: "row", alignItems: "center", gap: 8, flex: 1 }}>
                      <View style={[styles.iconWrap, { backgroundColor: colors.sageSoft }]}><DirIcon size={16} color={colors.primary} /></View>
                      <T style={{ fontFamily: fonts.bodySemi, fontSize: 15, flex: 1 }}>{pretty(e.archetype, ARCHETYPE_LABEL) || "Letter"}</T>
                    </View>
                    {e.status ? <Badge label={pretty(e.status).toUpperCase()} tone={STATUS_TONE[e.status] || "neutral"} /> : null}
                  </View>
                  <T variant="small" style={{ marginTop: 8 }}>
                    {inbound ? "From" : "To"} {pretty(e.recipient_type, RECIPIENT_LABEL) || "recipient"} · {fmt(e.created_at)}
                  </T>
                </Card>
              );
            })
          )}
        </ScrollView>
      )}
    </View>
  );
}

const styles = StyleSheet.create({
  iconWrap: { width: 34, height: 34, borderRadius: radius.pill, alignItems: "center", justifyContent: "center" },
});
