"""Unified tool export surface (Export Consolidation, Jun 2026).

One PDF path and one email path shared by every result-payload tool, so
each tool's "Save as PDF" / "Email to self" affordance hits the same
server-rendered PDF pipeline instead of a bespoke per-tool endpoint.

Endpoints
---------
POST /api/public/exports/pdf     , body {tool, payload, person_name?} → PDF blob
POST /api/public/exports/email   , body {tool, payload, to?, person_name?} → {ok}

Supported ``tool`` values: contribution, budget, invoice, care-plan.
(Classification Self-Check, Provider Price Checker and Letters &
Follow-ups keep their own dedicated server-rendered PDF endpoints; this
router covers the tools that previously had no export affordance.)
"""
from __future__ import annotations

import base64
import logging
from io import BytesIO
from typing import Any, Callable, Dict, Optional

from fastapi import APIRouter, Depends, HTTPException, Request, Response
from pydantic import BaseModel, EmailStr, Field

logger = logging.getLogger("wayly.tool_exports")


class ExportPdfRequest(BaseModel):
    tool: str = Field(max_length=40)
    payload: dict
    person_name: Optional[str] = Field(default=None, max_length=120)


class ExportEmailRequest(BaseModel):
    tool: str = Field(max_length=40)
    payload: dict
    to: Optional[EmailStr] = None
    person_name: Optional[str] = Field(default=None, max_length=120)


# --- per-tool PDF adapters -------------------------------------------------

def _render_contribution(payload: dict, person_name: Optional[str]) -> bytes:
    from services.ce2_pdf import render_ce2_pdf
    return render_ce2_pdf(result=payload, person_name=person_name)


def _render_budget(payload: dict, person_name: Optional[str]) -> bytes:
    from services.budget_pdf import render_budget_pdf
    return render_budget_pdf(result=payload, person_name=person_name)


def _render_invoice(payload: dict, person_name: Optional[str]) -> bytes:
    from services.inv1_check_report_pdf import render_invoice_check_report
    invoice = {
        "provider_name": payload.get("provider_name"),
        "provider_abn": payload.get("provider_abn"),
        "invoice_date": payload.get("invoice_date"),
        "due_date": payload.get("due_date"),
        "document_shape": payload.get("document_shape"),
    }
    reconciliation = payload.get("reconciliation") or {}
    return render_invoice_check_report(invoice=invoice, reconciliation=reconciliation)


def _render_care_plan(payload: dict, person_name: Optional[str]) -> bytes:
    from services.care_plan_pdf import render_artefact_pdf
    buf = BytesIO()
    render_artefact_pdf(
        buf,
        plan={},
        extraction=payload.get("extraction") or {},
        findings=payload.get("findings") or [],
    )
    return buf.getvalue()


# tool → (renderer, filename_base, subject, paid-plan label)
_REGISTRY: Dict[str, tuple] = {
    "contribution": (_render_contribution, "contribution_estimate",
                     "Your Wayly Contribution Estimate", "Contribution Estimator"),
    "budget": (_render_budget, "budget_lifetime_cap",
               "Your Wayly Budget & Lifetime Cap", "Budget Calculator"),
    "invoice": (_render_invoice, "invoice_check_report",
                "Your Wayly Invoice Check", "Invoice Checker"),
    "care-plan": (_render_care_plan, "care_plan_review",
                  "Your Wayly Care Plan Review", "Care Plan Reviewer"),
}


def _email_html(subject: str) -> str:
    return f"""<!doctype html>
<html><body style="font-family:Helvetica,Arial,sans-serif;background:#FBF8F3;padding:24px;color:#1C2B2D">
<table align="center" style="width:600px;max-width:100%;background:#fff;border-radius:12px;border:1px solid #E7E0D5;overflow:hidden">
<tr><td style="padding:20px 28px;background:#0E4D52;color:#fff">
  <div style="font-family:Georgia,serif;font-size:22px">Wayly</div>
  <div style="font-size:11px;letter-spacing:.08em;text-transform:uppercase;opacity:.85;margin-top:4px">Aged care, made easy</div>
</td></tr>
<tr><td style="padding:24px 28px">
  <h2 style="margin:0 0 12px;font-family:Georgia,serif;color:#0E4D52">{subject}</h2>
  <p style="font-size:14px;line-height:1.6">Your full result is attached as a PDF. Keep it for your records or take it to your next provider meeting.</p>
  <hr style="border:0;border-top:1px solid #E7E0D5;margin:20px 0" />
  <p style="margin:0;font-size:13px;color:#524B42">This is a plain-English summary generated by Wayly. It is guidance only, not financial or legal advice. Verify against your original provider records before acting.</p>
</td></tr>
<tr><td style="padding:16px 28px;background:#F4EFE7;color:#888;font-size:11px">
  Sent because you requested it from Wayly. wayly.com.au
</td></tr>
</table>
</body></html>"""


def build_tool_exports_router(
    *,
    require_paid_plan: Callable[..., Any],
    user_dep: Optional[Callable] = None,
) -> APIRouter:
    router = APIRouter(tags=["exports"])

    def _lookup(tool: str):
        entry = _REGISTRY.get(tool)
        if not entry:
            raise HTTPException(status_code=400, detail=f"Unknown export tool: {tool}")
        return entry

    async def _current_email(request: Request) -> Optional[str]:
        if user_dep is None:
            return None
        try:
            user = await user_dep(request)
            return (user or {}).get("email")
        except Exception:
            return None

    @router.post("/public/exports/pdf")
    async def export_pdf(body: ExportPdfRequest, request: Request, response: Response):
        renderer, fname_base, _subject, label = _lookup(body.tool)
        await require_paid_plan(request, response, label)
        try:
            pdf_bytes = renderer(body.payload, body.person_name)
        except Exception as e:
            logger.exception("export pdf render failed for %s: %s", body.tool, e)
            raise HTTPException(status_code=500, detail="PDF render failed")
        safe = (body.person_name or "wayly").replace(" ", "_").replace("/", "_")[:40] or "wayly"
        return Response(
            content=pdf_bytes,
            media_type="application/pdf",
            headers={
                "Content-Disposition": f'attachment; filename="{safe}_{fname_base}.pdf"',
                "Content-Length": str(len(pdf_bytes)),
            },
        )

    @router.post("/public/exports/email")
    async def export_email(body: ExportEmailRequest, request: Request, response: Response):
        renderer, fname_base, subject, label = _lookup(body.tool)
        await require_paid_plan(request, response, label)
        to = str(body.to) if body.to else await _current_email(request)
        if not to:
            raise HTTPException(status_code=400, detail="Please sign in to email this to yourself.")
        try:
            from email_service import _send, _sender  # type: ignore
        except Exception as e:
            logger.exception("email deps import failed: %s", e)
            raise HTTPException(status_code=503, detail="Email unavailable")
        try:
            pdf_bytes = renderer(body.payload, body.person_name)
        except Exception as e:
            logger.exception("export email render failed for %s: %s", body.tool, e)
            raise HTTPException(status_code=500, detail="PDF render failed")
        result = await _send({
            "from": _sender(),
            "to": [to],
            "subject": subject,
            "html": _email_html(subject),
            "attachments": [{
                "filename": f"{fname_base}.pdf",
                "content": base64.b64encode(pdf_bytes).decode("ascii"),
            }],
        })
        if not result.get("ok"):
            raise HTTPException(status_code=502, detail=f"Email failed: {result.get('reason')}")
        return {"ok": True, "id": result.get("id"), "mocked": bool(result.get("mocked"))}

    return router
